---

- name: request certificate for host
  command: ipa-getcert request -r -w \
    -I "{{ item }}" -N "CN={{ item }}" -D "{{ item }}" \
    -k "{{ ansemjo_ipa_getcert_storage_key }}/{{ item }}.key" \
    -f "{{ ansemjo_ipa_getcert_storage_crt }}/{{ item }}.crt" \
    -K "host/{{ item }}"
  
  args:
    creates: "{{ ansemjo_ipa_getcert_storage_crt }}/{{ item }}.crt"

  with_items: "{{ ansemjo_ipa_getcert_request_hostnames }}"
  
  register: certificate_request


- name: symlink fqdn certificate as 'localhost'
  file:
    state: link
    force: true
    src: "{{ item.src }}"
    path: "{{ item.path }}"

  with_items:

    - src: "{{ ansemjo_ipa_getcert_storage_key }}/{{ ansible_fqdn }}.key"
      path: "{{ ansemjo_ipa_getcert_storage_key }}/localhost.key"
    
    - src: "{{ ansemjo_ipa_getcert_storage_crt }}/{{ ansible_fqdn }}.crt"
      path: "{{ ansemjo_ipa_getcert_storage_crt }}/localhost.crt"

  when: (certificate_request is succeeded) and (ansemjo_ipa_getcert_symlink_fqdn)
